services:
  fan-files:
    container_name: fan-files
    build: .
    image: mobufan/fan-files:latest
    restart: unless-stopped
    networks:
      - fan-files
    ports:
      - 8678:80
    volumes:
      - fan-files:/flux/vault
      - /vol2/1000:/flux/vault2
    command:
      - --root=/flux/vault
    environment:
      - FB_EXTRAROOTS=/flux/vault2:存储空间2
      - FB_REDIS_CACHE_URL=redis://default:fan-files@redis:6379 # Use rediss:// for ssl
      - HTTP_PROXY=http://10.10.10.252:7893
      - HTTPS_PROXY=http://10.10.10.252:7893
      - NO_PROXY=172.17.0.1,127.0.0.1,localhost,10.10.10.0/24

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - fan-files
    command:
      - sh
      - -c
      - |
        cat > /tmp/users.acl <<EOF
        user default on >fan-files ~* +@all
        EOF
        redis-server --aclfile /tmp/users.acl

networks:
  fan-files:

volumes:
  fan-files:
